# github repository actions 페이지에 나타날 이름
name: CI for front using github actions

# event trigger
# develop 브랜치에 pull_request가 닫히거나 푸시했을때 실행
on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ "release" ]

permissions:
  contents: read

jobs:
  front-ci:
    runs-on: ubuntu-latest
    steps:
      # 저장소 코드를 체크아웃합니다. (PR 올린 코드를 가져오는 행위)
      - uses: actions/checkout@v4

      # Node.js 환경 설정
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # 지정된 Node.js 버전 사용
          cache: npm # setup-node 의 캐시 기능을 사용함
          cache-dependency-path: package-lock.json # 캐시 기능을 사용할 때 캐시의 기준이 될 파일을 지정

      - name: Install Dependencies
        run: npm install

      - name: Build with npm
        run: npm run build-only